export const botList = [
  {
    colorSchemes: {
      background: '#fcebe6',
      border: '#bc6850',
      base: '#ef9b83',
      stroke: '#bc6850',
    },
    id: 1684977998905,
    x: 3,
    y: 6,
    name: 'alen',
    booleanValue: 0,
    direction: 'west',
  },
  {
    colorSchemes: {
      background: '#eff7ee',
      border: '#7ba577',
      base: '#aed8aa',
      stroke: '#7ba577',
    },
    id: 1684978013028,
    x: 5,
    y: 0,
    name: 'hana',
    booleanValue: 1,
    direction: 'north',
  },
  {
    colorSchemes: {
      background: '#f1f6fc',
      border: '#869ebc',
      base: '#b9d1ef',
      stroke: '#869ebc',
    },
    id: 1684978024961,
    x: 5,
    y: 2,
    name: 'josh',
    booleanValue: 1,
    direction: 'west',
  },
  {
    colorSchemes: {
      background: '#fcfbf9',
      border: '#bcbaae',
      base: '#efede1',
      stroke: '#bcbaae',
    },
    id: 1684978031930,
    x: 6,
    y: 1,
    name: 'ami',
    booleanValue: 1,
    direction: 'south',
  },
];
export const BotData = [
  {
    id: Date.now(),
    name: 'alen',
    x: 7,
    y: 5,
    direction: 'north',
    speed: 500,
    booleanValue: 0,
    color: '#EF5350',
    bColor: '#B91C19',
    bgColor: '#FFC8C7',
  },
  {
    id: 2,
    x: 0,
    y: 0,
    direction: 'south',
    speed: 500,
    booleanValue: 0,
    color: '#42A5F5',
    bColor: '#1C78C2',
    bgColor: '#D0EAFF',
  },
  {
    id: 3,
    x: 4,
    y: 7,
    direction: 'north',
    speed: 500,
    booleanValue: 0,
    color: '#F6D62A',
    bColor: '#BAA11D',
    bgColor: '#FFF3B6',
  },
  {
    id: 4,
    x: 0,
    y: 4,
    direction: 'north',
    speed: 500,
    booleanValue: 0,
    color: '#3EC2BC',
    bColor: '#137D78',
    bgColor: '#C7FFFD',
  },
];
